### ISSUE TITLE
prompt 가 큰 경우 문제가 생기는 것 같습니다.

### ISSUE THREAD

**Issue by byeongal** [ainize-team/ServingLLMFastCelery#5]
7743 자의 prompt 를 입력으로 했는데 에러가 발생 합니다.

**Comment by byeongal** [comment]
@godhw 확인 부탁 드리겠습니다.

**Comment by godhw** [comment]
api서버에 에러 핸들링하는 코드에 문제가 있었습니다.
추가적으로, worker 서버에도 max token을 핸들링하는 과정도 문제가 있었습니다.
